---
# group_vars/haproxy.yml
# Variáveis dos nós HAProxy

haproxy_stats_port:      "{{ lookup('env', 'HAPROXY_STATS_PORT')     | default('8404',    true) }}"
haproxy_stats_user:      "{{ lookup('env', 'HAPROXY_STATS_USER')     | default('admin',   true) }}"
haproxy_stats_password:  "{{ lookup('env', 'HAPROXY_STATS_PASSWORD') | default('changeme', true) }}"
haproxy_http_port:       "{{ lookup('env', 'HAPROXY_HTTP_PORT')      | default('80',      true) }}"
haproxy_https_port:      "{{ lookup('env', 'HAPROXY_HTTPS_PORT')     | default('443',     true) }}"
haproxy_connect_timeout: "{{ lookup('env', 'HAPROXY_CONNECT_TIMEOUT')| default('10s',    true) }}"
haproxy_client_timeout:  "{{ lookup('env', 'HAPROXY_CLIENT_TIMEOUT') | default('60s',    true) }}"
haproxy_server_timeout:  "{{ lookup('env', 'HAPROXY_SERVER_TIMEOUT') | default('60s',    true) }}"

# Keepalived
keepalived_vrrp_id:       "{{ lookup('env', 'KEEPALIVED_VRRP_ID')       | default('51',      true) }}"
keepalived_vrrp_password: "{{ lookup('env', 'KEEPALIVED_VRRP_PASSWORD') | default('changeme', true) }}"
keepalived_interface:     "{{ lookup('env', 'KEEPALIVED_INTERFACE')     | default('eth1',    true) }}"
keepalived_master_priority: "{{ lookup('env', 'KEEPALIVED_MASTER_PRIORITY') | default('101', true) }}"
keepalived_backup_priority: "{{ lookup('env', 'KEEPALIVED_BACKUP_PRIORITY') | default('100', true) }}"
